# Generated by Django 3.0.5 on 2020-05-03 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arabicapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessoncard',
            name='card_title',
            field=models.CharField(default='Lesson Card', max_length=200),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='lesson_level',
            field=models.CharField(choices=[('BEGINNER', 'BEGINNER'), ('INTERMEDIATE', 'INTERMEDIATE'), ('PROFESSIONAL', 'PROFESSIONAL'), ('OTHER', 'OTHER')], max_length=20),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='lesson_type',
            field=models.CharField(choices=[('LISTENING', 'LISTENING'), ('READING', 'READING'), ('WRTING', 'WRTING'), ('SPEAKING', 'SPEAKING'), ('MISCELLANEOUS', 'MISCELLANEOUS')], max_length=20),
        ),
        migrations.AlterField(
            model_name='lessoncard',
            name='card_type',
            field=models.CharField(choices=[('AUDIO', 'AUDIO'), ('VIDEO', 'VIDEO'), ('ANIMATION', 'ANIMATION'), ('IMAGE', 'IMAGE'), ('PDF', 'PDF'), ('MISCELLANEOUS', 'MISCELLANEOUS')], max_length=20),
        ),
    ]
